---

- name: Play to install apache2
  hosts: all
  become: true
  tasks:

    - name: Install or update apache and php packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: true
