---

- name: Play to install apache2
  hosts: all
  become: true
  tasks:

    - name: Update respository index
      ansible.builtin.apt:
        update_cache: true

    - name: Install apache2 package
      ansible.builtin.apt: # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
        name: apache2
        state: present

    - name: Add php support for apache2
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: present

    - name: Upgrade packages
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        only_upgrade: true # <- Upgrades but does not install additional packages.
