---

- name: Play to uninstall apache2
  hosts: all
  become: true
  tasks:

    - name: Remove apache2 package
      ansible.builtin.apt: # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
        name: apache2
        state: absent

    - name: Remove php support for apache2
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent
