#
# Description: web_server task book
# Path:     /roles/web_server/tasks/main.yml
# Requires: /roles/web_server/handlers/main.yml
#           /roles/web_server/files/default_site.html
#

- name: Install apache and php packages
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: present

- name: Start apache
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: Change e-mail address for admin (CentOS)
  tags: apache, centos
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  notify:
    - Restart apache

- name: Copy default html file for site
  tags: apache
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
