---

- name: Play to install apache2
  hosts: all
  become: true
  tasks:

    - name: Install or update apache and php packages
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install or update apache and php packages
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: true
      when: ansible_distribution == "CentOS"
