#
# Description: workstations task book
# Path:     /roles/workstations/handlers/main.yml
#

- name: Install terraform
  tags: terraform
  ansible.builtin.unarchive:
    src: "{{ terraform_archive_name }}"
    dest: "{{ terraform_path }}"
    remote_src: true
    mode: "0755"
    owner: root
    group: root
