#
# Description: db_servers task book
# Path:     /roles/db_servers/tasks/main.yml
#

- name: Install mariadb
  tags: mariadb
  ansible.builtin.package:
    name: "{{ db_package_name }}"
    state: present
